apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k2e4e42x8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:1790c9acab73497b5e1c4e47adf48e83b9c7daa5@sha256:a6bd4b68f29a9d75b3a6760125e0b6d8356a0f460c09deb6155436a28d8e8aca
          name: container-image
