apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k2e4e42x8-go
  janus-idp.io/tekton: k2e4e42x8-go
  backstage.io/kubernetes-id: k2e4e42x8-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k2e4e42x8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
